version: '3'

services:

  bonb:
    build: .
    command: npm run prod
    depends_on:
      - bonb-mongo
    ports:
      - 80:3000
      - 443:3000
    env_file:
      - prod.env
  
  bonb-mongo:
    restart: always
    image: mongo
    volumes:
      - ./vol/bonb-mongo:/data/db